### ISSUE TITLE
Component throws on unmount

### ISSUE THREAD

**Issue by otbe** [jonathandion/react-tilt#1]
Hi,

very nice tilt component, works very well!
I guess there is a problem while unmounting Tilt. It is possible that some of the delayed executions (via setTimeout/requestAnimationFrame) will be executed after the component is unmounted, which will result in a React warning caused by ```setState``` calls.

Something like
```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Tilt component.
```

I was able to solve this problem by adding some tear down logic:
```
componentWillUnmount() {
   clearTimeout(this.transitionTimeout);
   cancelAnimationFrame(this.updateCall);
}
```

Should I prepare a PR?

Thanks!

**Comment by jonathandion** [comment]
Hey Benjamin,

Thank you for your feedback and for the quick fix.

**Comment by sahilchopra** [comment]
Hi 

I am getting same error

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Tilt component.

on reset function
`  }, {
    key: 'reset',
    value: function reset() {
      var _this2 = this;

      window.requestAnimationFrame(function () {
        _this2.setState(Object.assign({}, _this2.state, {
          style: _extends({}, _this2.state.style, {
            transform: "perspective(" + _this2.settings.perspective + "px) " + "rotateX(0deg) " + "rotateY(0deg) " + "scale3d(1, 1, 1)" })
        }));
      });
    }
  },`

Even i have added above mentioned logic on unMount 

componentWillUnmount() {
   clearTimeout(this.transitionTimeout);
   cancelAnimationFrame(this.updateCall);
}

Can you please help me in that
