### ISSUE TITLE
FindDOMNode is deprecated

### ISSUE THREAD

**Issue by rramadista** [jonathandion/react-tilt#17]
FindDOMNode is deprecated in react strict mode.

**Comment by EnzoH8321** [comment]
Yes, also getting the same issue.

**Comment by Lima-Tembe** [comment]
I am having the same issue too!

**Comment by Samuel-Morgan-Tyghe** [comment]
change the line to "const myNode = ReactDOM.findDOMNode(this);"

**Comment by jonathandion** [comment]
Please upgrade to the latest version. Issues is fixed. Thanks.
