### ISSUE TITLE
Support react 17

### ISSUE THREAD

**Issue by andreasjacobsen93** [jonathandion/react-tilt#19]
The project needs to update its dependencies to also support react 17.
The current code seems to work with react 17, so it should just be a change in the package.json.

**Comment by KunalTanwar11** [comment]
@andreasjacobsen93 totally agree with you current version is not supporting react 17.

**Comment by w3bdesign** [comment]
You guys may be interested in this one: 

https://github.com/jonahallibone/react-tilty

@andreasjacobsen93  @KunalTanwar

**Comment by jonathandion** [comment]
Fixed in v1.0.0

**Comment by w3bdesign** [comment]
I believe we need React 18 support now?

@jonathandion

**Comment by jonathandion** [comment]
@w3bdesign it's already supported.
