### ISSUE TITLE
Something strange happens with scrolling

### ISSUE THREAD

**Issue by bernatfortet** [jonathandion/react-tilt#5]
In the demo: https://vx-demo.now.sh/gallery

try scrolling down while trying to keep the mouse over the tilt element.

You will see how the tilting get's stuck on one of the sides.

I'm going to try to use the basic library. But thought I'd let you know.

**Comment by jonathandion** [comment]
Thanks for the feedback. I will take a look.

**Comment by philippehenoch** [comment]
Any updates on this?

**Comment by jonathandion** [comment]
@bernatfortet Still an issue?

**Comment by bernatfortet** [comment]
Can't replicate it. So I guess it's fine now?
I'll open an issue again if I detect the same problem again.

Thanks
